name: test run scratch
 
# Definition when the workflow should run
on:
  # The workflow will run whenever an event happens on a pull request test
  pull_request:
    types: [opened, synchronize]

jobs:
  validate_scratch_deploy:
    runs-on: ubuntu-latest
    steps:
      # Install Salesforce CLI
      - name: "Install Salesforce CLI"
        run: | 
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sf --version
      # Checkout the code in the pull request
      - name: "Checkout source code"
        uses: actions/checkout@v3
      # Load secret for dev hub
      - name: "Populate auth file with SFDX_URL secret"
        shell: bash
        run: "echo ${{ secrets.DEVHUB_SFDX_URL}} > ./SFDX_URL_STORE.txt"
      # run: echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
      - name: "Authenticate with dev hub"
        run: |
          sf org login sfdx-url -f ./SFDX_URL_STORE.txt -a devhub -d
      #sf org create scratch -d -f config/project-scratch-def.json -a  my-scratch-org1 --duration-days 1
      # run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username="nikita.ashok-panchgale780@agentforce.com" --set-default-dev-hub
      # Create a scratch org
      - name: "List the Orgs"
        run: "sf org list"
      # Deploy Project Manifest
      - name: "Deploy Metadata"
        run: "sf project deploy start --manifest manifest/package.xml --target-org  my-scratch-org1"
